services:
  gateh8:
    image: yarlson/gateh8:0.3.0
    ports:
      - "80:80"
    environment:
      - HOST1=nginx1
      - HOST2=nginx2
    volumes:
      - ./config.json:/config.json
    command: ["-a", ":80"]
    depends_on:
      - nginx1
      - nginx2

  nginx1:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index1.html:/usr/share/nginx/html/index.html

  nginx2:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index2.html:/usr/share/nginx/html/index.html
